### ISSUE TITLE
megadl didn't work for me

### ISSUE THREAD

**Issue by darachm** [sirselim/guppy_parameter_optimiser#2]
The command to use megadl to pull down the input data didn't work for me, got error message:

    WARNING: Skipping invalid Mega download link: https://mega.nz/file/nAkFHAZR#hFc2ELBxNlXV8MfGaAuuP8nXfoEHBwvk1obnO-LkZTI
    
Was able to download in browser and upload to guppy computer though.

Does it work for others? Downloading in California.

**Comment by sirselim** [comment]
Thanks for the report. I've heard from a few others having similar issue, largely to do with institutional network/security policies. I have a new data set that I'm looking to upload to a better platform (or a few platforms) but just need the time to do so.

**Comment by mshamash** [comment]
This should work!

`megadl 'https://mega.nz/#!nAkFHAZR!hFc2ELBxNlXV8MfGaAuuP8nXfoEHBwvk1obnO-LkZTI'`
